-- WB CMDB信息表
CREATE TABLE IF NOT EXISTS `wb_cmdb_info` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `system_name` VARCHAR(100) NOT NULL COMMENT '系统名称',
  `environment` VARCHAR(50) DEFAULT NULL COMMENT '环境',
  `ip_address` VARCHAR(50) DEFAULT NULL COMMENT 'IP地址',
  `port` VARCHAR(20) DEFAULT NULL COMMENT '端口',
  `status` VARCHAR(20) DEFAULT NULL COMMENT '状态',
  `owner` VARCHAR(100) DEFAULT NULL COMMENT '负责人',
  `remark` TEXT DEFAULT NULL COMMENT '备注',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_system_name` (`system_name`),
  INDEX `idx_environment` (`environment`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='WB CMDB信息表';

-- VB CMDB信息表
CREATE TABLE IF NOT EXISTS `vb_cmdb_info` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `system_name` VARCHAR(100) NOT NULL COMMENT '系统名称',
  `environment` VARCHAR(50) DEFAULT NULL COMMENT '环境',
  `ip_address` VARCHAR(50) DEFAULT NULL COMMENT 'IP地址',
  `port` VARCHAR(20) DEFAULT NULL COMMENT '端口',
  `status` VARCHAR(20) DEFAULT NULL COMMENT '状态',
  `owner` VARCHAR(100) DEFAULT NULL COMMENT '负责人',
  `remark` TEXT DEFAULT NULL COMMENT '备注',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_system_name` (`system_name`),
  INDEX `idx_environment` (`environment`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='VB CMDB信息表';
